version: "3"

services:
  redis:
    image: redis:7
    container_name: redis_app
  app:
    build:
      context: .
    env_file:
      - .env_docker
    container_name: fastapi_app
    ports:
      - 8000:8000
    depends_on:
      - redis